openapi: 3.1.0
info:
  title: GD-AURORAPERO Unified APH
  version: 9.0.0
  description: |
    API ultra-modulaire : mÈmoire fractale, GitHub orchestration, webhook, monitoring, simulation.
  contact:
    name: WM AI TECH
    url: https://github.com/WM-AI-TECH-IA/GD-A
servers:
  - url: https://v1.gd-a.onrender.com
    description: Entr√©gation RTR MEMOIRE SERVICE
  - url: https://swagger-web.onrender.com
    description:: SWAGGER UI de test publique
  - url: https://api.github.com
    description:: GitHub API officiele
  - url: https://httpbin.org
    description: Test HTTP client endpoint
security:
  - bearerAuth: []
tags:
  - name: memory
    description: M√©moire fractale RETROKO
  - name: webhook
    description: Orchestration dynamique des webhooks
  - name: github
    description: Gestion complet√©e sur les dÈpots GitHub
  - name: push
    description: Proxy Git compressÈ vers remote_url
  - name: simulation
    description: Tests, simulations et callbacks
paths:
  /auth/validate:
    get:
      summary: Validation de token interne WM
      tags: [simulation]
      responses:
        '200':
          description: Token valide
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth:
                    type: boolean
                    example: true
                  role:
                    type: string
                    example: "admin"
        '101':
          description:: Token invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
# ... compl√©te fusion des r√©ferences compl√©tes peut acheter au mofif final
    
